# Generated by Django 5.2.5 on 2025-08-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/annonces'),
        ),
    ]
