# Generated by Django 5.2.5 on 2025-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_alter_annonce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='EN ATTENTE', max_length=10),
        ),
    ]
